import { and, desc, eq, like, sql } from "drizzle-orm";
import { getDatabaseClient } from "@/app/utils";
import { quotes, workflowEvents } from "@/db/schema";

export interface AgentStats {
	callbackCount: number;
	errorCount: number;
	lastCallbackAt?: Date;
}

/**
 * Get stats for the Risk Verification Agent
 * Source: workflow_events
 */
export async function getRiskAgentStats(): Promise<AgentStats> {
	const db = getDatabaseClient();
	if (!db) return { callbackCount: 0, errorCount: 0 };

	const stepId = "ai-fica-verification";

	// Count successful runs (stage_change events with payload containing step)
	const successResult = await db
		.select({ count: sql<number>`count(*)` })
		.from(workflowEvents)
		.where(
			and(
				eq(workflowEvents.eventType, "stage_change"),
				like(workflowEvents.payload, `%${stepId}%`)
			)
		);

	// Count errors
	const errorResult = await db
		.select({ count: sql<number>`count(*)` })
		.from(workflowEvents)
		.where(
			and(
				eq(workflowEvents.eventType, "error"),
				like(workflowEvents.payload, `%${stepId}%`)
			)
		);

	// Get last activity
	const lastEvent = await db
		.select()
		.from(workflowEvents)
		.where(
			and(
				eq(workflowEvents.eventType, "stage_change"),
				like(workflowEvents.payload, `%${stepId}%`)
			)
		)
		.orderBy(desc(workflowEvents.timestamp))
		.limit(1);

	return {
		callbackCount: successResult[0].count,
		errorCount: errorResult[0].count,
		lastCallbackAt: lastEvent[0]?.timestamp || undefined,
	};
}

/**
 * Get stats for the Quote Generator Agent
 * Source: quotes table (success) and workflow_events (errors)
 */
export async function getQuoteAgentStats(): Promise<AgentStats> {
	const db = getDatabaseClient();
	if (!db) return { callbackCount: 0, errorCount: 0 };

	// Count successful quotes generated by Gemini
	const successResult = await db
		.select({ count: sql<number>`count(*)` })
		.from(quotes)
		.where(eq(quotes.generatedBy, "gemini"));

	// Count errors (step: generate-legal-pack)
	const errorResult = await db
		.select({ count: sql<number>`count(*)` })
		.from(workflowEvents)
		.where(
			and(
				eq(workflowEvents.eventType, "error"),
				like(workflowEvents.payload, `%"step":"generate-legal-pack"%`)
			)
		);

	// Get last activity
	const lastQuote = await db
		.select()
		.from(quotes)
		.where(eq(quotes.generatedBy, "gemini"))
		.orderBy(desc(quotes.createdAt))
		.limit(1);

	return {
		callbackCount: successResult[0].count,
		errorCount: errorResult[0].count,
		lastCallbackAt: lastQuote[0]?.createdAt || undefined,
	};
}
