import { type EventSchemas } from "inngest";
import type { WorkflowStatus } from "@/inngest/steps/database";
import type { FormType } from "@/db/schema";

// ============================================
// Form Types for Events
// ============================================

export type FormSubmissionType =
	| "stratcol_agreement"
	| "facility_application"
	| "absa_6995"
	| "fica_documents";

export type DocumentVerificationResult = {
	documentId: number;
	documentType: string;
	status: "verified" | "rejected" | "pending";
	reason?: string;
};

// ============================================
// Event Definitions
// ============================================

export type Events = {
    // ================================================================
    // Lead & Workflow Events
    // ================================================================

    /** Triggered when a new lead is created and workflow starts */
    'onboarding/lead.created': {
        data: {
            leadId: number;
            workflowId: number;
        };
    };

    /** Legacy: Quality gate passed (replaced by contract/signed) */
    'onboarding/quality-gate-passed': {
        data: {
            workflowId: number;
            approverId: string;
            timestamp: string;
        };
    };

    /** Agent callback received from external system */
    'onboarding/agent-callback': {
        data: {
            workflowId: number;
            decision: {
                agentId: string;
                outcome: 'APPROVED' | 'REJECTED';
                reason?: string;
                timestamp: string;
            };
        };
    };

    /** Human resolved a timeout situation */
    'onboarding/timeout-resolved': {
        data: {
            workflowId: number;
            action: 'retry' | 'cancel' | 'continue';
            decision?: {
                agentId: string;
                outcome: 'APPROVED' | 'REJECTED';
                reason?: string;
                timestamp: string;
            };
        };
    };

    /** Quote generated by external service */
    'onboarding/quote-generated': {
        data: {
            workflowId: number;
            leadId: number;
            quote: {
                quoteId: string;
                amount: number;
                terms: string;
            };
        };
    };

    /** Workflow error resolved by human */
    'workflow/error-resolved': {
        data: {
            workflowId: number;
            action: 'retry' | 'cancel' | 'continue';
            resolvedBy?: string; // User ID
        };
    };

    /** Contract signed by client */
    'contract/signed': {
        data: {
            workflowId: number;
            contractUrl?: string;
            signedAt: string;
        };
    };

    // ================================================================
    // ITC Credit Check Events
    // ================================================================

    /** ITC credit check completed */
    'itc/check.completed': {
        data: {
            workflowId: number;
            leadId: number;
            result: {
                creditScore: number;
                riskCategory: 'LOW' | 'MEDIUM' | 'HIGH' | 'VERY_HIGH';
                passed: boolean;
                recommendation: 'AUTO_APPROVE' | 'MANUAL_REVIEW' | 'AUTO_DECLINE' | 'ENHANCED_DUE_DILIGENCE';
                referenceNumber?: string;
            };
            timestamp: string;
        };
    };

    // ================================================================
    // FICA Document Events
    // ================================================================

    /** FICA documents uploaded by client */
    'upload/fica.received': {
        data: {
            workflowId: number;
            leadId: number;
            documents: Array<{
                type: 'BANK_STATEMENT' | 'ACCOUNTANT_LETTER' | 'ID_DOCUMENT' | 'PROOF_OF_ADDRESS';
                filename: string;
                url: string;
                uploadedAt: string;
            }>;
            uploadedBy?: string;
        };
    };

    /** AI FICA analysis completed */
    'fica/analysis.completed': {
        data: {
            workflowId: number;
            leadId: number;
            analysis: {
                aiTrustScore: number;
                recommendation:
                    | 'APPROVE'
                    | 'APPROVE_WITH_CONDITIONS'
                    | 'MANUAL_REVIEW'
                    | 'REQUEST_ADDITIONAL_DOCS'
                    | 'DECLINE';
                riskFlagsCount: number;
                nameMatchVerified: boolean;
                accountMatchVerified: boolean;
                summary: string;
            };
            timestamp: string;
        };
    };

    // ================================================================
    // Risk Decision Events
    // ================================================================

    /** Risk Manager made a decision */
    'risk/decision.received': {
        data: {
            workflowId: number;
            leadId: number;
            decision: {
                outcome: 'APPROVED' | 'REJECTED' | 'REQUEST_MORE_INFO';
                decidedBy: string; // Risk Manager email/ID
                reason?: string;
                conditions?: string[];
                timestamp: string;
            };
        };
    };

    // ================================================================
    // V24 Integration Events
    // ================================================================

    /** Client profile created in V24 */
    'v24/client.created': {
        data: {
            workflowId: number;
            leadId: number;
            v24Response: {
                success: boolean;
                clientId?: string;
                v24Reference?: string;
                error?: string;
            };
            timestamp: string;
        };
    };

    /** Training session scheduled */
    'v24/training.scheduled': {
        data: {
            workflowId: number;
            leadId: number;
            session: {
                sessionId: string;
                scheduledDate: string;
                meetingLink?: string;
            };
        };
    };

    /** Welcome pack sent to client */
    'v24/welcome.sent': {
        data: {
            workflowId: number;
            leadId: number;
            sentTo: string; // Email
            timestamp: string;
        };
    };

	// ============================================
	// Form Submission Events
	// ============================================

	/**
	 * Fired when a form is submitted (not draft)
	 */
	"onboarding/form-submitted": {
		data: {
			workflowId: number;
			formType: FormSubmissionType;
			submissionId: number;
		};
	};

	/**
	 * Fired when all required forms for a stage are submitted
	 */
	"onboarding/forms-complete": {
		data: {
			workflowId: number;
			stage: number;
			formTypes: FormSubmissionType[];
		};
	};

	/**
	 * Fired when a form is approved during review
	 */
	"onboarding/form-approved": {
		data: {
			workflowId: number;
			formType: FormSubmissionType;
			reviewerId: string;
			timestamp: string;
		};
	};

	/**
	 * Fired when a form is rejected during review
	 */
	"onboarding/form-rejected": {
		data: {
			workflowId: number;
			formType: FormSubmissionType;
			reviewerId: string;
			reason: string;
			timestamp: string;
		};
	};

	// ============================================
	// Document Verification Events
	// ============================================

	/**
	 * Fired when documents are submitted for verification
	 */
	"onboarding/documents-submitted": {
		data: {
			workflowId: number;
			documentIds: number[];
		};
	};

	/**
	 * Fired when document verification is complete
	 */
	"onboarding/documents-verified": {
		data: {
			workflowId: number;
			verificationResults: DocumentVerificationResult[];
			allPassed: boolean;
		};
	};

	/**
	 * Fired when automated validation completes (EFS24, BizPortal, sanctions)
	 */
	"onboarding/validation-complete": {
		data: {
			workflowId: number;
			leadId: number;
			validationType: "identity" | "entity" | "risk" | "social";
			passed: boolean;
			details: Record<string, unknown>;
		};
	};
};
