// ============================================
// Form Types for Events
// ============================================

export type FormSubmissionType =
	| "stratcol_agreement"
	| "facility_application"
	| "absa_6995"
	| "fica_documents";

export type DocumentVerificationResult = {
	documentId: number;
	documentType: string;
	status: "verified" | "rejected" | "pending";
	reason?: string;
};

// ============================================
// Event Definitions
// ============================================

export type Events = {
	// ================================================================
	// Applicant & Workflow Events
	// ================================================================

	/** Triggered when a new applicant is created - starts Control Tower workflow */
	"onboarding/lead.created": {
		data: {
			applicantId: number;
			workflowId: number;
		};
	};

	/** Legacy: Quality gate passed (replaced by contract/signed) */
	"onboarding/quality-gate-passed": {
		data: {
			workflowId: number;
			approverId: string;
			timestamp: string;
		};
	};

	/** Agent callback received from external system */
	"onboarding/agent-callback": {
		data: {
			workflowId: number;
			decision: {
				agentId: string;
				outcome: "APPROVED" | "REJECTED";
				reason?: string;
				timestamp: string;
			};
		};
	};

	/** Human resolved a timeout situation */
	"onboarding/timeout-resolved": {
		data: {
			workflowId: number;
			action: "retry" | "cancel" | "continue";
			decision?: {
				agentId: string;
				outcome: "APPROVED" | "REJECTED";
				reason?: string;
				timestamp: string;
			};
		};
	};

	/** Quote generated by external service */
	"onboarding/quote-generated": {
		data: {
			workflowId: number;
			applicantId: number;
			quote: {
				quoteId: string;
				amount: number;
				terms: string;
			};
		};
	};

	/** Quote approved by staff and sent to client */
	"quote/approved": {
		data: {
			workflowId: number;
			applicantId: number;
			quoteId: number;
			approvedAt: string;
		};
	};

	/** Quote rejected by staff (overlimit or other reason) */
	"quote/rejected": {
		data: {
			workflowId: number;
			applicantId: number;
			quoteId: number;
			reason: string;
			isOverlimit: boolean;
			rejectedBy: string;
			rejectedAt: string;
		};
	};

	/** Quote signed by client */
	"quote/signed": {
		data: {
			workflowId: number;
			applicantId: number;
			quoteId: number;
			signedAt: string;
		};
	};

	/** Applicant feedback received on quote */
	"quote/feedback.received": {
		data: {
			workflowId: number;
			applicantId: number;
			quoteId: number;
			feedback: {
				accepted: boolean;
				comments?: string;
				requestedChanges?: string[];
			};
			receivedAt: string;
		};
	};

	/** Workflow error resolved by human */
	"workflow/error-resolved": {
		data: {
			workflowId: number;
			action: "retry" | "cancel" | "continue";
			resolvedBy?: string; // User ID
		};
	};

	/** Contract signed by client */
	"contract/signed": {
		data: {
			workflowId: number;
			contractUrl?: string;
			signedAt: string;
		};
	};

	/** Form submitted by client */
	"form/submitted": {
		data: {
			workflowId: number;
			applicantId: number;
			formType: string;
			applicantMagiclinkFormId: number;
			submittedAt: string;
		};
	};

	/** Accountant letter form submitted */
	"form/accountant-letter.submitted": {
		data: {
			workflowId: number;
			applicantId: number;
			submissionId: number;
			submittedAt: string;
		};
	};

	/** Call centre application form submitted */
	"form/call-centre.submitted": {
		data: {
			workflowId: number;
			applicantId: number;
			submissionId: number;
			submittedAt: string;
		};
	};

	/** Risk manager confirmed financial statements received (high-risk applicants) */
	"risk/financial-statements.confirmed": {
		data: {
			workflowId: number;
			applicantId: number;
			confirmedBy: string;
			confirmedAt: string;
		};
	};

	/** Facility application form submitted - triggers mandate determination */
	"form/facility.submitted": {
		data: {
			workflowId: number;
			applicantId: number;
			submissionId: number;
			formData: {
				mandateVolume: number;
				mandateType: "EFT" | "DEBIT_ORDER" | "CASH" | "MIXED";
				businessType: string;
				annualTurnover?: number;
			};
			submittedAt: string;
		};
	};

	/** Document uploaded by client */
	"document/uploaded": {
		data: {
			workflowId: number;
			applicantId: number;
			documentId: number;
			documentType: string;
			category?: string;
			uploadedAt: string;
		};
	};

	/** Document processed by AI/agent */
	"document/processed": {
		data: {
			workflowId: number;
			applicantId: number;
			documentId: number;
			documentType: string;
			status: "processed" | "failed";
			processedAt: string;
		};
	};

	// ================================================================
	// ITC Credit Check Events
	// ================================================================

	/** ITC credit check completed */
	"itc/check.completed": {
		data: {
			workflowId: number;
			applicantId: number;
			result: {
				creditScore: number;
				riskCategory: "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH";
				passed: boolean;
				recommendation:
					| "AUTO_APPROVE"
					| "MANUAL_REVIEW"
					| "AUTO_DECLINE"
					| "ENHANCED_DUE_DILIGENCE";
				referenceNumber?: string;
			};
			timestamp: string;
		};
	};

	// ================================================================
	// FICA Document Events
	// ================================================================

	/** FICA documents uploaded by client */
	"upload/fica.received": {
		data: {
			workflowId: number;
			applicantId: number;
			documents: Array<{
				type: "BANK_STATEMENT" | "ACCOUNTANT_LETTER" | "ID_DOCUMENT" | "PROOF_OF_ADDRESS";
				filename: string;
				url: string;
				uploadedAt: string;
			}>;
			uploadedBy?: string;
		};
	};

	/** AI FICA analysis completed */
	"fica/analysis.completed": {
		data: {
			workflowId: number;
			applicantId: number;
			analysis: {
				aiTrustScore: number;
				recommendation:
					| "APPROVE"
					| "APPROVE_WITH_CONDITIONS"
					| "MANUAL_REVIEW"
					| "REQUEST_ADDITIONAL_DOCS"
					| "DECLINE";
				riskFlagsCount: number;
				nameMatchVerified: boolean;
				accountMatchVerified: boolean;
				summary: string;
			};
			timestamp: string;
		};
	};

	// ================================================================
	// Risk Decision Events
	// ================================================================

	/** Risk Manager made a decision */
	"risk/decision.received": {
		data: {
			workflowId: number;
			applicantId: number;
			decision: {
				outcome: "APPROVED" | "REJECTED" | "REQUEST_MORE_INFO";
				decidedBy: string; // Risk Manager email/ID
				reason?: string;
				conditions?: string[];
				timestamp: string;
			};
		};
	};

	/** Procurement check completed by Risk Manager */
	"risk/procurement.completed": {
		data: {
			workflowId: number;
			applicantId: number;
			procureCheckResult: {
				riskScore: number;
				anomalies: string[];
				recommendedAction: "APPROVE" | "MANUAL_REVIEW" | "DECLINE";
				rawData?: Record<string, unknown>;
			};
			decision: {
				outcome: "CLEARED" | "DENIED";
				decidedBy: string;
				reason?: string;
				timestamp: string;
			};
		};
	};

	// ================================================================
	// Mandate & Document Events
	// ================================================================

	/** Internal event: mandate type determined from facility application */
	"mandate/determined": {
		data: {
			workflowId: number;
			applicantId: number;
			mandateType: "EFT" | "DEBIT_ORDER" | "CASH" | "MIXED";
			requiredDocuments: string[];
			requiresProcurementCheck: boolean;
		};
	};

	/** Mandate-specific documents submitted */
	"document/mandate.submitted": {
		data: {
			workflowId: number;
			applicantId: number;
			mandateType: "EFT" | "DEBIT_ORDER" | "CASH" | "MIXED";
			documents: Array<{
				documentId: number;
				documentType: string;
				fileName: string;
				uploadedAt: string;
			}>;
			allRequiredDocsReceived: boolean;
		};
	};

	// ================================================================
	// V24 Integration Events
	// ================================================================

	/** Client profile created in V24 */
	"v24/client.created": {
		data: {
			workflowId: number;
			applicantId: number;
			v24Response: {
				success: boolean;
				clientId?: string;
				v24Reference?: string;
				error?: string;
			};
			timestamp: string;
		};
	};

	/** Training session scheduled */
	"v24/training.scheduled": {
		data: {
			workflowId: number;
			applicantId: number;
			session: {
				sessionId: string;
				scheduledDate: string;
				meetingLink?: string;
			};
		};
	};

	/** Welcome pack sent to client */
	"v24/welcome.sent": {
		data: {
			workflowId: number;
			applicantId: number;
			sentTo: string; // Email
			timestamp: string;
		};
	};

	// ============================================
	// Form Submission Events
	// ============================================

	/**
	 * Fired when a form is submitted (not draft)
	 */
	"onboarding/form-submitted": {
		data: {
			workflowId: number;
			formType: FormSubmissionType;
			submissionId: number;
		};
	};

	/**
	 * Fired when all required forms for a stage are submitted
	 */
	"onboarding/forms-complete": {
		data: {
			workflowId: number;
			stage: number;
			formTypes: FormSubmissionType[];
		};
	};

	/**
	 * Fired when a form is approved during review
	 */
	"onboarding/form-approved": {
		data: {
			workflowId: number;
			formType: FormSubmissionType;
			reviewerId: string;
			timestamp: string;
		};
	};

	/**
	 * Fired when a form is rejected during review
	 */
	"onboarding/form-rejected": {
		data: {
			workflowId: number;
			formType: FormSubmissionType;
			reviewerId: string;
			reason: string;
			timestamp: string;
		};
	};

	// ============================================
	// Document Verification Events
	// ============================================

	/**
	 * Fired when documents are submitted for verification
	 */
	"onboarding/documents-submitted": {
		data: {
			workflowId: number;
			documentIds: number[];
		};
	};

	/**
	 * Fired when document verification is complete
	 */
	"onboarding/documents-verified": {
		data: {
			workflowId: number;
			verificationResults: DocumentVerificationResult[];
			allPassed: boolean;
		};
	};

	/**
	 * Fired when automated validation completes (EFS24, BizPortal, sanctions)
	 */
	"onboarding/validation-complete": {
		data: {
			workflowId: number;
			applicantId: number;
			validationType: "identity" | "entity" | "risk" | "social";
			passed: boolean;
			details: Record<string, unknown>;
		};
	};

	/**
	 * Final approval button pressed by Account Manager - ends workflow
	 */
	"onboarding/final-approval.received": {
		data: {
			workflowId: number;
			applicantId: number;
			approvedBy: string; // Account Manager ID
			contractSigned: boolean;
			absaFormComplete: boolean;
			notes?: string;
			timestamp: string;
		};
	};

	/**
	 * AI analysis aggregation completed (bank validation, sanctions, risk)
	 */
	"onboarding/ai-analysis.completed": {
		data: {
			workflowId: number;
			applicantId: number;
			analysis: {
				bankValidation: {
					verified: boolean;
					accountHolder?: string;
					accountNumber?: string;
					flags: string[];
				};
				sanctionsCheck: {
					passed: boolean;
					matchesFound: number;
					details?: string;
				};
				riskAnalysis: {
					overallScore: number;
					category: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
					flags: string[];
				};
			};
			aggregatedScore: number;
			recommendation: "APPROVE" | "MANUAL_REVIEW" | "DECLINE";
			timestamp: string;
		};
	};

	// ================================================================
	// Kill Switch / Workflow Termination Events
	// ================================================================

	/**
	 * Kill switch activated - workflow terminated immediately
	 * This event signals all parallel processes to halt
	 */
	"workflow/terminated": {
		data: {
			workflowId: number;
			applicantId: number;
			reason: "PROCUREMENT_DENIED" | "COMPLIANCE_VIOLATION" | "FRAUD_DETECTED" | "MANUAL_TERMINATION";
			decidedBy: string;
			terminatedAt: string;
			notes?: string;
		};
	};

	/**
	 * Workflow termination check - used by parallel processes to verify status
	 */
	"workflow/termination-check": {
		data: {
			workflowId: number;
			checkingProcess: string;
		};
	};

	// ================================================================
	// Business Type & Document Events
	// ================================================================

	/**
	 * Business type determined from facility application
	 */
	"onboarding/business-type.determined": {
		data: {
			workflowId: number;
			applicantId: number;
			businessType: "NPO" | "PROPRIETOR" | "COMPANY" | "TRUST" | "BODY_CORPORATE" | "PARTNERSHIP" | "CLOSE_CORPORATION";
			requiredDocuments: string[];
			optionalDocuments: string[];
		};
	};

	/**
	 * Conditional documents requested based on business type
	 */
	"document/conditional-request.sent": {
		data: {
			workflowId: number;
			applicantId: number;
			businessType: string;
			documentsRequested: string[];
			sentAt: string;
		};
	};

	// ================================================================
	// AI Agent Events
	// ================================================================

	/**
	 * Validation agent completed document analysis
	 */
	"agent/validation.completed": {
		data: {
			workflowId: number;
			applicantId: number;
			validationScore: number;
			documentsValidated: number;
			passed: number;
			failed: number;
			recommendation: "PROCEED" | "REVIEW_REQUIRED" | "STOP";
		};
	};

	/**
	 * Risk agent completed financial analysis
	 */
	"agent/risk.completed": {
		data: {
			workflowId: number;
			applicantId: number;
			riskScore: number;
			riskCategory: "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH";
			recommendation: "APPROVE" | "CONDITIONAL_APPROVE" | "MANUAL_REVIEW" | "DECLINE";
			flags: string[];
		};
	};

	/**
	 * Sanctions agent completed compliance screening
	 */
	"agent/sanctions.completed": {
		data: {
			workflowId: number;
			applicantId: number;
			riskLevel: "CLEAR" | "LOW" | "MEDIUM" | "HIGH" | "BLOCKED";
			passed: boolean;
			isPEP: boolean;
			requiresEDD: boolean;
			adverseMediaCount: number;
		};
	};

	/**
	 * Aggregated AI analysis completed (all agents)
	 */
	"agent/analysis.aggregated": {
		data: {
			workflowId: number;
			applicantId: number;
			aggregatedScore: number;
			canAutoApprove: boolean;
			requiresManualReview: boolean;
			isBlocked: boolean;
			recommendation: "AUTO_APPROVE" | "PROCEED_WITH_CONDITIONS" | "MANUAL_REVIEW" | "BLOCK";
			flags: string[];
		};
	};
};
