#!/usr/bin/env bun

/**
 * Test script for /api/quotes endpoint
 * Simulates Zapier webhook payload from Gemini AI
 */

const API_URL = "http://localhost:3000/api/quotes";

// Sample payload matching Zapier workflow output
const testPayload = {
	workflowId: 3,
	amount: 750000, // $7,500 in cents
	baseFeePercent: 150, // 1.50% in basis points
	adjustedFeePercent: 200, // 2.00% in basis points (risk-adjusted)
	generatedBy: "gemini",
};

async function testQuoteCreation() {
	console.log("🧪 Testing /api/quotes endpoint...\n");
	console.log("📤 Sending payload:");
	console.log(JSON.stringify(testPayload, null, 2));
	console.log();

	try {
		const response = await fetch(API_URL, {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify(testPayload),
		});

		const data = await response.json();

		console.log(`📊 Response Status: ${response.status}`);
		console.log("📥 Response Data:");
		console.log(JSON.stringify(data, null, 2));
		console.log();

		if (response.ok) {
			console.log("✅ Test PASSED - Quote created successfully!");
			console.log(`   Quote ID: ${data.quote.id}`);
			console.log(`   Workflow ID: ${data.quote.workflowId}`);
			console.log(`   Amount: $${data.quote.amount / 100}`);
			console.log(`   Base Fee: ${data.quote.baseFeePercent} bps`);
			console.log(`   Adjusted Fee: ${data.quote.adjustedFeePercent} bps`);
			console.log(`   Generated By: ${data.quote.generatedBy}`);
			console.log(`   Status: ${data.quote.status}`);
		} else {
			console.log("❌ Test FAILED");
			if (data.details) {
				console.log("   Validation errors:", data.details);
			}
		}
	} catch (error) {
		console.error("❌ Test FAILED with error:");
		console.error(error);
	}
}

// Run the test
testQuoteCreation();
